[package]
name = "reshell-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.4"
fork = "0.1.22"
glob = "0.3.1"
indexmap = "2.0.2"
parsy = "0.2.11"
rand = "0.8.5"
reshell-parser = { path = "../parser" }
reshell-checker = { path = "../checker" }
terminal_size = "0.3.0"
