[package]
name = "reshell-wasm-syntax-highlighter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
reshell-syntax-highlighter = { path = "../../crates/syntax-highlighter" }
