[package]
name = "reshell-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
parsy = "0.9.2"
reshell-parser = { path = "../parser" }
reshell-shared = { version = "0.1.0", path = "../shared" }
