[package]
name = "reshell-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
parsy = "0.14.5"
reshell-parser = { path = "../parser" }
reshell-prettify = { version = "0.1.0", path = "../prettify" }
